--- # Install apache or httpd 
  - name: install httpd
    package:
      name: httpd
      state: latest
    notify:
    - restart httpd
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: install apache2
    package:
      name: apache2
      state: latest
    notify:
    - restart apache2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: create virtual host
    template: src=virtualhost.conf.j2 dest=/etc/httpd/sites-enabled/{{ domain }}.conf
    notify:
    - restart httpd
    when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

  - name: create virtual host
    template: src=virtualhost.conf.j2 dest=/etc/apache2/sites-enabled/{{ domain }}.conf
    notify:
    - restart apache2
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
